language: python
python: 
  - "3.7"
install: 
  - "pip install -r requirements.txt"
services:
  - postgresql
before_script:
  - psql -c 'create database hiware;' -U postgres
  - export DATABASE_URL="postgres://postgres@localhost:5432/hiware"
script:
  - SECRET_KEY="whatever" ./manage.py test