# Generated by Django 2.2.7 on 2019-11-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191119_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
