# Generated by Django 3.0 on 2019-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_baseproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
