# Generated by Django 3.0 on 2019-12-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191213_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BaseProduct'),
        ),
    ]
