# Generated by Django 3.0 on 2019-12-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191216_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.Category'),
        ),
    ]
