# Generated by Django 3.0 on 2019-12-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191219_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseproduct', to='products.BaseProduct'),
        ),
    ]
